### ISSUE TITLE
Cross-site scripting flaw

### ISSUE THREAD

**Issue by markboolootian** [DNS-OARC/p5-DSC#28]
We received an external report of a cross-site scripting issue in DSC.  One of our security folks had a look and made the below suggestions regarding a fix which I'm posting here for possible future inclusion.  Examples of leveraging said XSS issue look like:

https://www.example.com/cgi-bin/dsc-grapher.pl?plot=<script>alert(1)</script>
https://www.example.com/cgi-bin/dsc-grapher.pl?server=<script>alert(1)</script>
https://www.example.com/cgi-bin/dsc-grapher.pl?node=<script>alert(1)</script>

It appears the flaw is in the perl5 DSC [module](https://github.com/DNS-OARC/p5-DSC)
 
A fix for these specific issues could be implemented via a couple minor code changes.
 
Specifically, line [983](https://github.com/DNS-OARC/p5-DSC/blob/develop/DSC/grapher.pm#L983) of grapher.pm is where the content from the user-provided parameters is output to the user... 
 
 
`983: print "<h2>$0 ERROR</h2><p>$msg\n";
` 

A fix can be implemented with two line changes:
 
1) Changing line 983 to read as below:
 
`983: print "<h2>$0 ERROR</h2><p>", HTML::Entities::encode($msg), "\n"
` 

2) And adding the following line somewhere in the file (can put it almost anywhere, but top of file or near line 983 probably makes the most sense):
 
`use HTML::Entities ();
`

**Comment by jelu** [comment]
Thanks for the report, will roll out v2.04 ASAP!
